FROM node:lts-alpine as builder
WORKDIR /vue-project
ADD ./package.json ./
RUN npm install

COPY . .
RUN npm run build

FROM nginx:alpine

COPY default.conf /etc/nginx/nginx.conf

## Remove default nginx index page
RUN rm -rf /usr/share/nginx/html/*

# Copy from the stahg 1
COPY --from=bulder /vue-project/dist /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]