FROM node:lts-alpine as builder
WORKDIR /vue-project
ADD ./package.json ./
RUN npm install

COPY . .
RUN npm run build

FROM nginx:alpine

RUN mkdir /app

COPY --from=builder ./vue-project/nginx.conf /etc/nginx/nginx.conf

# Copy from the stahg 1
COPY --from=builder ./vue-project/dist /app
CMD ["nginx", "-g", "daemon off;"]