FROM node:lts-alpine as builder
WORKDIR /vue-project
ADD ./package.json ./
RUN npm install

COPY . .
RUN npm run build

FROM nginx:alpine

COPY default.conf /etc/nginx/nginx.conf

RUN rm -rf /etc/nginx/conf.d/default.conf
COPY --from=builder ./vue-project/default.conf /etc/nginx/conf.d/default.conf

RUN rm -rf /usr/share/nginx/html/*

# Copy from the stahg 1
COPY --from=builder ./vue-project/dist /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]