FROM python:3.8.13

ENV PYTHONDONTWRITEVYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /

RUN pip install -U pip \
    && apt-get update \
    && apt install -y curl netcat \
    && curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
ENV PATH="${PATH}:/root/.poetry/bin"

COPY poetry.lock /poetry.lock
COPY pyproject.toml /pyproject.toml
COPY uwsgi.ini /uwsgi.ini
COPY ./ /

RUN poetry install

ENV SSL_DISABLE=1

CMD ["poetry", "run", "uwsgi", "./uwsgi.ini", "--http", ":80"]

