FROM python:3.10.1

ENV PYTHONDONTWRITEVYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /flask-project

RUN pip install -U pip \
    && apt-get update \
    && apt install -y curl netcat \
    && curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
ENV PATH="${PATH}:/root/.poetry/bin"

COPY poetry.lock /flask-project/poetry.lock
COPY pyproject.toml /flask-project/pyproject.toml
COPY app/config.py /flask-project/Config.py
COPY ./ /flask-project/

RUN poetry install

ENV FLASK_APP="app.py"
ENV FLASK_DEBUG=1
ENV SSL_DISABLE=1

CMD ["poetry", "run", "flask", "run", "--host", "0.0.0.0", "--port", "8000"]

